%---------------------------------------------------------------------------------------------------
\chapter{Resumen ejecutivo}
\label{chp_res_ejec}

%---------------------------------------------------------------------------------------------------
\section{Objeto del estudio}
\label{chp_res_ejec:objeto}


%---------------------------------------------------------------------------------------------------------

\section{Resumen de prestaciones}
\label{chp_res_ejec:res_pres}


%----------------------------------------------------------------------------------------------------------

\section{Hipótesis claves}
\label{chp_res_ejec:hip_claves}

En la siguiente tabla se presentan las principales hipótesis que han sido establecidas en el presente estudio en base a sus comportamientos históricos (ver capítulo \ref{chp_contexto})


%---------------------------------------------------------------------------------------------------
\section{Recomendaciones}
\label{chp_conclusion:recomendacion}

