%---------------------------------------------------------------------------------------------------
\chapter[Análisis demográfico, de salarios y pensiones]{Análisis demográfico, de salarios y pensiones}
\label{chp_demog}
%--------------------------------------------------------------------------------------------------
% Población Afiliada y Pensionistas del SGO

 A continuación presentamos un análisis tabular y gráfico de las principales variables demográficas de la población asegurada y beneficiaria.

\section{Estructura demográfica de la población afiliada}

