# Creación estructura reporte ----------------------------------------------------------------------
if ( dir.exists( parametros$resultado_seguro ) ) {
  unlink( parametros$resultado_tablas, recursive = TRUE, force = TRUE )
  unlink( parametros$resultado_graficos, recursive = TRUE, force = TRUE )
  unlink( parametros$resultado_seguro, recursive = TRUE, force = TRUE )

}
dir.create( parametros$resultado_seguro )
dir.create( parametros$resultado_tablas )
dir.create( parametros$resultado_graficos )


REP_file_latex_org <- c( paste( parametros$work_dir, 'Reportes/hombre.png', sep = '' ),
                         paste( parametros$work_dir, 'Reportes/mujer.png', sep = '' ),
                         paste( parametros$work_dir, 'Reportes/Ciencias.png', sep = '' ),
                         paste( parametros$work_dir, 'Reportes/EPN.png', sep = '' ),
                         paste( parametros$work_dir, 'Reportes/PaqueteR.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/NuevoPaqueteR.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/git.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/funciones.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/pruebafunciones.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/existe.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/check.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/familia.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/pruebadata.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/urls.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/github.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/DESCRIPTION.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/Archivos_Rd.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/NAMESPACE.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/doc_data.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/pkgdown.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/website.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/check_data_funciones.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/urlwebsite.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/github_1.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/github_2.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/github_3.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/github_4.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/github_5.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/minty.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/varbslib.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/tema.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/ws-barra-nave.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/t-f.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/footer.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/linkautor.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/README.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/SW-dev.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/web-readme.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/logo.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/weblogo.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/ord-func.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/vTuto.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/vi-tuto.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/ws_vt.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/viñeta-tutorial.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/v-article.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/ws-va.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/ws-va1.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/fb.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/fr.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/tw.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/yt.png', sep = ''),
                         paste( parametros$work_dir, 'Reportes/news.png', sep = '')
)

REP_file_latex_des <- c( paste( parametros$resultado_seguro, 'graficos/hombre.png', sep = '' ),
                         paste( parametros$resultado_seguro, 'graficos/mujer.png', sep = '' ),
                         paste( parametros$resultado_seguro, 'graficos/Ciencias.png', sep = '' ),
                         paste( parametros$resultado_seguro, 'graficos/EPN.png', sep = '' ),
                         paste( parametros$resultado_seguro, 'graficos/PaqueteR.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/NuevoPaqueteR.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/git.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/funciones.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/pruebafunciones.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/existe.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/check.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/familia.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/pruebadata.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/urls.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/github.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/DESCRIPTION.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/Archivos_Rd.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/NAMESPACE.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/doc_data.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/pkgdown.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/website.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/check_data_funciones.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/urlwebsite.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/github_1.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/github_2.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/github_3.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/github_4.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/github_5.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/minty.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/varbslib.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/tema.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/ws-barra-nave.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/t-f.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/footer.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/linkautor.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/README.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/SW-dev.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/web-readme.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/logo.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/weblogo.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/ord-func.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/vTuto.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/vi-tuto.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/ws_vt.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/viñeta-tutorial.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/v-article.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/ws-va.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/ws-va1.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/fb.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/fr.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/tw.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/yt.png', sep = ''),
                         paste( parametros$resultado_seguro, 'graficos/news.png', sep = '')
)

file.copy( REP_file_latex_org, REP_file_latex_des, overwrite = TRUE  )
